application: environment-scotland
version: 0-6

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: frontend/css
- url: /fonts
  static_dir: frontend/fonts
- url: /images
  static_dir: frontend/images
- url: /js
  static_dir: frontend/js
- url: /$
  static_files: frontend/index.html
  upload: frontend/index.html
- url: /(.*\.(html|js|css|gif))$
  static_files: frontend/\1
  upload: frontend/.*\.(html|js|css|gif)$
- url: /sparql/current/query\.json.*
  script: dot.rural.sepake.httpserver.application
- url: /crawl/.*
  script: dot.rural.sepake.httpserver.application
  login: admin

builtins:
  - appstats: on
  
libraries:
- name: webapp2
  version: latest
- name: lxml
  version: latest
  