application: environment-scotland
version: 0-7

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: frontend/css
- url: /fonts
  static_dir: frontend/fonts
- url: /images
  static_dir: frontend/images
- url: /js
  static_dir: frontend/js
- url: /sparql-queries
  static_dir: frontend/sparql-queries
- url: /sparql-backend
  static_dir: frontend/sparql-backend
- url: /$
  static_files: frontend/search.html
  upload: frontend/search.html
- url: /(.*\.(html|js|css|gif))$
  static_files: frontend/\1
  upload: frontend/.*\.(html|js|css|gif)$
- url: /(sparql|search)/.*
  script: dotruralsepake.httpserver.application
- url: /(harvest|index|delete)/.*
  script: dotruralsepake.httpserver.application
  login: admin

admin_console:
  pages:
  - name: Delete all documents in the main dataset, add the new data
    url: /delete/default?overwriteBy=newdata
  - name: Index all documents in the main dataset
    url: /index/default

builtins:
  - appstats: on
  
libraries:
- name: webapp2
  version: latest
- name: lxml
  version: latest
  